# Generated by Django 6.0.4 on 2026-04-19 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='description',
        ),
        migrations.AddField(
            model_name='trip',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='title',
            field=models.CharField(default='Trip', max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=models.ImageField(default='default_travel.jpg', upload_to='trip_images/'),
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('activity_title', models.CharField(max_length=200)),
                ('activity_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Excursion', 'Excursion'), ('Sights', 'Sights'), ('Shopping', 'Shopping'), ('Hotel', 'Hotel')], default='Sights', max_length=50)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='trips.trip')),
            ],
        ),
    ]
