# Generated by Django 6.0.4 on 2026-04-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_trip_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={'ordering': ['day_number']},
        ),
        migrations.AddField(
            model_name='itinerary',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='category',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Sights', 'Sights'), ('Transport', 'Transport'), ('Food', 'Food'), ('Shopping', 'Shopping')], max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trip',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
