# Generated by Django 6.0.4 on 2026-04-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_alter_itinerary_options_itinerary_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='cost',
            new_name='cost_estimate',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='activity_time',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='category',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='description',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='description',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='image',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='title',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='location_address',
            field=models.CharField(default='Unknown', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerary',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='time_slot',
            field=models.CharField(default='10:00 AM - 06:00 PM', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='image_list',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='trip',
            name='total_days',
            field=models.IntegerField(default=1),
        ),
    ]
