# Generated by Django 6.0.4 on 2026-04-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_rename_cost_itinerary_cost_estimate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='traveler_name',
            field=models.CharField(default='User', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='total_days',
            field=models.IntegerField(),
        ),
    ]
