# Generated by Django 6.0.4 on 2026-04-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_trip_traveler_name_alter_trip_total_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='traveler_name',
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='cost_estimate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='total_days',
            field=models.IntegerField(default=1),
        ),
    ]
