# Generated by Django 6.0.4 on 2026-04-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_remove_trip_traveler_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='cost_estimate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
