# Generated by Django 6.0.4 on 2026-04-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_alter_itinerary_cost_estimate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='cost_estimate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
