# Generated by Django 6.0.4 on 2026-05-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_alter_itinerary_cost_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cost_estimate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
